name: build-wasm-and-deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build WASM
        run: |
          export GOOS=js GOARCH=wasm
          mkdir -p docs
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js docs/
          go build -o docs/auction-game.wasm ./wasm

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
